export let TRIPS = [
  {
    id: 1,
    name: "Halong Bay Full-Day Boat Cruise",
    price_adult: 55,
    price_child: 41.25,
    time: "12h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "8 AM English Commentary Tour",
    thumb: "assets/img/trip/thumb/trip_1.jpeg",
    description: "Sail through incredible islands, spectacular limestone karsts, and unique grottos on this day tour from Hanoi. Swim or relax on the sun deck and take in the panoramic views of the magnificent Halong Bay. \n Depart from your Hanoi hotel for Halong Bay and, upon arrival, embark on a traditional junk boat. Admire the serene natural settings while you enjoy a delicious seafood lunch onboard.",
    location: "Halong Bay, Halong, Vietnam",
    images: [
      "assets/img/trip/trip_5.jpeg",
      "assets/img/trip/trip_6.jpeg",
      "assets/img/trip/trip_7.jpeg",
      "assets/img/trip/trip_8.jpeg",
    ],
    highlights: [
      "UNESCO-listed World Heritage Site of Halong Bay",
      "A cruise along the many spectacular limestone islands",
      "Opportunity to swim in clear waters & explore the grottos",
      "Stunning views while relaxing on the sun deck",
      "Fresh seafood lunch provided onboard",
    ]
  },
  {
    id: 2,
    name: "Private City Full-Day Tour with Electric Car Ride",
    price_adult: 55,
    price_child: 41.25,
    time: "12h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "8 AM English Commentary Tour",
    thumb: "assets/img/trip/thumb/trip_2.jpeg",
    description: "Sail through incredible islands, spectacular limestone karsts, and unique grottos on this day tour from Hanoi. Swim or relax on the sun deck and take in the panoramic views of the magnificent Halong Bay. \n Depart from your Hanoi hotel for Halong Bay and, upon arrival, embark on a traditional junk boat. Admire the serene natural settings while you enjoy a delicious seafood lunch onboard.",
    location: "Halong Bay, Halong, Vietnam",
    images: [],
    highlights: []
  },
  {
    id: 3,
    name: "Private City Morning Tour",
    price_adult: 55,
    price_child: 41.25,
    time: "12h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "8 AM English Commentary Tour",
    thumb: "assets/img/trip/thumb/trip_3.jpeg",
    description: "Sail through incredible islands, spectacular limestone karsts, and unique grottos on this day tour from Hanoi. Swim or relax on the sun deck and take in the panoramic views of the magnificent Halong Bay. \n Depart from your Hanoi hotel for Halong Bay and, upon arrival, embark on a traditional junk boat. Admire the serene natural settings while you enjoy a delicious seafood lunch onboard.",
    location: "Halong Bay, Halong, Vietnam",
    images: [],
    highlights: []
  },
  {
    id: 4,
    name: "Perfume Pagoda Full-Day Tour",
    price_adult: 55,
    price_child: 41.25,
    time: "12h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "8 AM English Commentary Tour",
    thumb: "assets/img/trip/thumb/trip_4.jpeg",
    description: "Sail through incredible islands, spectacular limestone karsts, and unique grottos on this day tour from Hanoi. Swim or relax on the sun deck and take in the panoramic views of the magnificent Halong Bay. \n Depart from your Hanoi hotel for Halong Bay and, upon arrival, embark on a traditional junk boat. Admire the serene natural settings while you enjoy a delicious seafood lunch onboard.",
    location: "Halong Bay, Halong, Vietnam",
    images: [],
    highlights: []
  }
]
